### ISSUE TITLE
Nächster Webmontag am Montag, steht aber Dienstag da

### ISSUE THREAD

**Issue by ronald** [WebmontagSN/webmontag-schwerin.de#5]
http://webmontag-schwerin.de/
IST: Next Dienstag | 16. November 2015
SOLL: Next Montag | 16. November 2015

**Comment by ronald** [comment]
fixed in 782616b

Neuer Helper: fmt_date.
Wenn mit String aufgerufen fmt_date("Oktober"), wird der einfach ausgeben.
Wenn mit Datum aufgerufen (in yml steht 2015-11-16), wird formatiert als "16. November 2015"
Wenn mit Datum aufgerufen und 2. Parameter ist :prepend_dow, erfolgt Ausgabe als "Montag | 16. November 2015"

**Comment by michamilz** [comment]
👍
